parameters:
    kafka_default_brokers: ['%env(KAFKA_DEFAULT_BROKER_ONE)%', '%env(KAFKA_DEFAULT_BROKER_TWO)%', '%env(KAFKA_DEFAULT_BROKER_THREE)%']
sts_gaming_group_kafka:
    consumers:
        instances:
            App\Consumer\HealthCheckConsumer:
                brokers: '%kafka_default_brokers%'
                group_id: '%env(KAFKA_DEFAULT_GROUP_ID)%'
                topics: ['%env(KAFKA_HEALTH_CHECK_TOPIC)%']
                decoder: StsGamingGroup\KafkaBundle\Decoder\PlainDecoder
            App\Consumer\UserRegisteredConsumer:
                brokers: '%kafka_default_brokers%'
                group_id: '%env(KAFKA_DEFAULT_GROUP_ID)%'
                topics: [ '%env(KAFKA_USER_REGISTERED_TOPIC)%' ]
                decoder: StsGamingGroup\KafkaBundle\Decoder\JsonDecoder
                denormalizer: App\Denormalizer\UserRegisteredDenormalizer
    producers:
        instances:
            App\Producer\HealthCheckProducer:
                brokers: '%kafka_default_brokers%'
                producer_topic: '%env(KAFKA_HEALTH_CHECK_TOPIC)%'
            App\Producer\UserRegisteredProducer:
                brokers: '%kafka_default_brokers%'
                producer_topic: '%env(KAFKA_USER_REGISTERED_TOPIC)%'
