version: "3.5"
services:
  php:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/vendor
      - ./docker/php-cli/php-cli-ini-overrides.ini:/etc/php/8.0/cli/conf.d/99-overrides.ini
